/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Modelo.Consultas;
import Modelo.Hash;
import Modelo.Logeo;
import com.sun.awt.AWTUtilities;
import static java.util.Objects.hash;
import javax.swing.JOptionPane;
import rojeru_san.RSPanelsSlider;


/**
 *
 * @author PC
 */
public class Intefaz_Login extends javax.swing.JFrame {

    /**
     * Creates new form Intefaz_Login
     */
    public Intefaz_Login() {
        this.setUndecorated(true);
        initComponents();
        this.setLocationRelativeTo(this);
        AWTUtilities.setWindowOpaque(this, false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rSPanelShadow3 = new rojeru_san.RSPanelShadow();
        jPanelbarraverde = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        rSPanelShadow1 = new rojeru_san.RSPanelShadow();
        jPanel1 = new javax.swing.JPanel();
        btncerrar = new rojeru_san.RSButtonRiple();
        rSPanelsSlider1 = new rojeru_san.RSPanelsSlider();
        panelSesion = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtUsuario = new rojeru_san.RSMTextFull();
        txtContra = new rojeru_san.RSMPassView();
        btniniciar = new rojeru_san.RSButton();
        confirmacion = new javax.swing.JLabel();
        PanelCargando = new javax.swing.JPanel();
        rSProgressMaterial1 = new rojerusan.componentes.RSProgressMaterial();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelbarraverde.setBackground(new java.awt.Color(0, 51, 51));
        jPanelbarraverde.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/logo (1).png"))); // NOI18N
        jPanelbarraverde.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 260, 190));

        rSPanelShadow3.add(jPanelbarraverde, java.awt.BorderLayout.CENTER);

        getContentPane().add(rSPanelShadow3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 290, 430));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btncerrar.setText("x");
        btncerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncerrarActionPerformed(evt);
            }
        });
        jPanel1.add(btncerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 0, 41, -1));

        jLabel1.setBackground(new java.awt.Color(0, 112, 192));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 112, 192));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Iniciar Sesion");
        jLabel1.setToolTipText("");

        txtUsuario.setModoMaterial(true);
        txtUsuario.setPlaceholder("Usuario");
        txtUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUsuarioActionPerformed(evt);
            }
        });

        txtContra.setModoMaterial(true);
        txtContra.setPlaceholder("Contraseña");

        btniniciar.setText("Iniciar");

        confirmacion.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        confirmacion.setForeground(new java.awt.Color(204, 0, 0));
        confirmacion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout panelSesionLayout = new javax.swing.GroupLayout(panelSesion);
        panelSesion.setLayout(panelSesionLayout);
        panelSesionLayout.setHorizontalGroup(
            panelSesionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelSesionLayout.createSequentialGroup()
                .addContainerGap(84, Short.MAX_VALUE)
                .addGroup(panelSesionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(confirmacion, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelSesionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelSesionLayout.createSequentialGroup()
                            .addGroup(panelSesionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtContra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(76, 76, 76))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelSesionLayout.createSequentialGroup()
                            .addComponent(btniniciar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(99, 99, 99)))))
        );
        panelSesionLayout.setVerticalGroup(
            panelSesionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSesionLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(confirmacion, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addComponent(txtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtContra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btniniciar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        rSPanelsSlider1.add(panelSesion, "card2");

        PanelCargando.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        PanelCargando.add(rSProgressMaterial1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 50, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 112, 192));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Cargando");
        PanelCargando.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(101, 227, 226, -1));

        rSPanelsSlider1.add(PanelCargando, "card3");

        jPanel1.add(rSPanelsSlider1, new org.netbeans.lib.awtextra.AbsoluteConstraints(292, 62, 410, 277));

        rSPanelShadow1.add(jPanel1, java.awt.BorderLayout.CENTER);

        getContentPane().add(rSPanelShadow1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 720, 360));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btncerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncerrarActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btncerrarActionPerformed

    private void txtUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUsuarioActionPerformed
    /*void btniniciarActionPerformed(java.awt.event.ActionEvent evt) {                                           
      Logeo mod = new Logeo();
        mod.setUsuario(txtUsuario.getText());
        String passw = new String(txtContra.getPassword());
        passw = Hash.md5(passw);
        mod.setPass(passw);
        Consultas consulta = new Consultas();
        if (consulta.Logeo(mod).equals("Administrador")) {
            JOptionPane.showMessageDialog(null, "Ingreso Correcto");
            Interfaz_home a = new Interfaz_home();
            a.setVisible(true);
            this.setVisible(false);
        }if (consulta.Logeo(mod).equals("Empleado")) {
            JOptionPane.showMessageDialog(null, "Ingreso Correcto");
            Interfaz_home a = new Interfaz_home();
            a.setVisible(true);
            this.setVisible(false);
        } 
        else {
            confirmacion.setText("¡Usuario o Contraseña incorrectos!");
        
    }                                          
   }*/
    public void iniciovistas(int num){
        if(num==1){
            Interfaz_home a = new Interfaz_home();
            a.setVisible(true);
            this.setVisible(false);
        }
        if(num==2){
            Interfaz_home a = new Interfaz_home();
            a.setVisible(true);
            this.setVisible(false);
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
       
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Intefaz_Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelCargando;
    private rojeru_san.RSButtonRiple btncerrar;
    public rojeru_san.RSButton btniniciar;
    public javax.swing.JLabel confirmacion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelbarraverde;
    private javax.swing.JPanel panelSesion;
    private rojeru_san.RSPanelShadow rSPanelShadow1;
    private rojeru_san.RSPanelShadow rSPanelShadow3;
    private rojeru_san.RSPanelsSlider rSPanelsSlider1;
    private rojerusan.componentes.RSProgressMaterial rSProgressMaterial1;
    public rojeru_san.RSMPassView txtContra;
    public rojeru_san.RSMTextFull txtUsuario;
    // End of variables declaration//GEN-END:variables
}
